name: Pull Request

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
        with:
            args:
                build -a -c --skip-tests --sourceroot ses-ballerina